Duplicate tasks for multiple stack associated buildpacks
Signed-off-by: Dimitris Karakasilis <DKarakasilis@suse.com>

diff --git a/brats/pipeline.yaml b/brats/pipeline.yaml
--- a/brats/pipeline.yaml
+++ b/brats/pipeline.yaml
@@ -1,4 +1,5 @@
 ---
+<% suse_stacks = ["sle12", "sle15"] %>
 <% buildpacks = ["ruby", "go", "python", "php", "nodejs", "staticfile", "nginx", "binary", "dotnet-core"] %>
 #resource_types:
 #- name: email
@@ -55,6 +56,18 @@ resources:
     access_key_id: {{aws-access-key}}
     secret_access_key: {{aws-secret-key}}
     private_key: {{github-private-key}}
+<% suse_stacks.each do |stack| %>
+- name: s3.suse-buildpacks-staging-<%= buildpack %>-<%= stack %>
+  type: s3
+  source:
+    bucket: suse-buildpacks-staging
+    # TODO: Switch to just using '-' when all the buildpacks have a '-' version.
+    #regexp: <%= buildpack %>-buildpack-v([0-9-.]+)-pre-[0-9a-f]{8}\.zip
+    regexp: <%= buildpack %>[-_]buildpack-<%= stack %>-v([0-9-.]+)-pre-[0-9a-f]{8}\.zip
+    access_key_id: {{aws-access-key}}
+    secret_access_key: {{aws-secret-key}}
+    private_key: {{github-private-key}}
+<% end %>
 - name: s3.cf-buildpacks.suse.com-<%= buildpack %>
   type: s3
   source:
@@ -67,12 +80,69 @@ resources:
 <% end %>
 jobs:
 <% buildpacks.each do |buildpack| %>
+- name: check-<%= buildpack %>-artifacts-published
+  plan:
+    - get: s3.suse-buildpacks-staging-<%= buildpack %>
+      trigger: true
+    <% suse_stacks.each do |stack| %>
+    - get: s3.suse-buildpacks-staging-<%= buildpack %>-<%= stack %>
+      trigger: true
+    <% end %>
+    - task: check
+      config:
+        platform: linux
+        image_resource:
+          type: registry-image
+          source:
+            repository: splatform/bosh-cli
+            tag: 761288a4a7202607e73bbcb57f6e89d940bf92be
+        inputs:
+          - name: s3.suse-buildpacks-staging-<%= buildpack %>
+          <% suse_stacks.each do |stack| %>
+          - name: s3.suse-buildpacks-staging-<%= buildpack %>-<%= stack %>
+          <% end %>
+        run:
+          path: bash
+          args:
+          - -exc
+          - |
+            set -e
+
+            file_version=""
+            for FILE in $(ls s3.suse-buildpacks-staging-*/*.zip); do
+              if [ "$file_version" != "" ]; then
+                [[ $FILE =~ -v([0-9\.]*) ]] && compare_version="${BASH_REMATCH[1]}"
+                if [ "$file_version" == "" ]; then
+                  echo "Couldn't match a version with our regexp (compare file). This is not expected. Exiting."
+                  exit 1
+                fi
+
+                if [ "$file_version" != "$compare_version" ]; then
+                  echo "The versions of the buidlpack artifcats don't match. Maybe OBS hasn't finished publishing yet? Give it some time."
+                  exit 1
+                fi
+              else
+                [[ $FILE =~ -v([0-9\.]*) ]] && file_version="${BASH_REMATCH[1]}"
+                if [ "$file_version" == "" ]; then
+                  echo "Couldn't match a version with our regexp. This is not expected. Exiting."
+                  exit 1
+                fi
+              fi
+            done
+            echo "Versions match. All artifacts are available."
+            exit 0
 - name: run-<%= buildpack %>-brats
   serial_groups: [tests]
   plan:
   - in_parallel:
     - get: s3.suse-buildpacks-staging-<%= buildpack %>
       trigger: true
+      passed:
+        - check-<%= buildpack %>-artifacts-published
+    <% suse_stacks.each do |stack| %>
+    - get: s3.suse-buildpacks-staging-<%= buildpack %>-<%= stack %>
+      trigger: true
+    <% end %>
     - get: ci
     - get: git.cf-<%= buildpack %>-buildpack-readonly
     - get: gh-release.<%= buildpack %>-buildpack
@@ -225,6 +295,7 @@ jobs:
 #      params:
 #        subject: mail-output/subject-failed.txt
 #        body: mail-output/body-failed.txt
+#
 - name: create-final-<%= buildpack %>-buildpack
   plan:
   - in_parallel:
@@ -264,6 +335,48 @@ jobs:
     params:
       file: s3-out/*.zip
       acl: public-read
+<% suse_stacks.each do |stack| %>
+- name: create-final-<%= buildpack %>-<%= stack %>-buildpack
+  plan:
+  - in_parallel:
+    - get: s3.suse-buildpacks-staging-<%= buildpack %>
+      trigger: true
+      passed:
+      - run-<%= buildpack %>-integration-tests
+    - get: s3.suse-buildpacks-staging-<%= buildpack %>-<%= stack %>
+    - get: ci
+    - get: git.cf-<%= buildpack %>-buildpack
+  - task: create-final-buildpack
+    input_mapping:
+      git.cf-buildpack: git.cf-<%= buildpack %>-buildpack
+      s3.suse-buildpacks-staging: s3.suse-buildpacks-staging-<%= buildpack %>-<%= stack %>
+    config:
+      platform: linux
+      image_resource:
+        type: registry-image
+        source:
+          repository: splatform/concourse-brats
+      inputs:
+        - name: ci
+        - name: git.cf-buildpack
+        - name: s3.suse-buildpacks-staging
+      outputs:
+        - name: s3-out
+      params:
+        BUILDPACK: <%= buildpack %>
+        STAGING_BUCKET_NAME: suse-buildpacks-staging
+        PRODUCTION_BUCKET_NAME: cf-buildpacks.suse.com
+        PRODUCTION_BUCKET_URL: "https://cf-buildpacks.suse.com"
+        AWS_ACCESS_KEY_ID: {{aws-access-key}}
+        AWS_SECRET_ACCESS_KEY: {{aws-secret-key}}
+        AWS_DEFAULT_REGION: us-east-1
+      run:
+        path: ci/brats/tasks/create-final-buildpack.sh
+  - put: s3.cf-buildpacks.suse.com-<%= buildpack %>
+    params:
+      file: s3-out/*.zip
+      acl: public-read
+<% end %>
 - name: add-manifest-and-tag-<%= buildpack %>-buildpack
   plan:
   - in_parallel:
@@ -333,7 +446,9 @@ jobs:
   - task: trigger-final-releases-pipeline
     input_mapping:
       git.cf-buildpack-release: git.cf-<%= buildpack %>-buildpack-release
-      s3.cf-buildpacks.suse.com: s3.cf-buildpacks.suse.com-<%= buildpack %>
+      <% suse_stacks.each do |stack| %>
+      s3.cf-buildpacks.suse.com.<%= stack %>: s3.cf-buildpacks.suse.com-<%= buildpack %>-<%= stack %>
+      <% end %>
     config:
       platform: linux
       image_resource:
@@ -343,9 +458,12 @@ jobs:
       inputs:
         - name: ci
         - name: git.cf-buildpack-release
-        - name: s3.cf-buildpacks.suse.com
+        <% suse_stacks.each do |stack| %>
+        - name: s3.cf-buildpacks.suse.com.<%= stack %>
+        <% end %>
       params:
         BUILDPACK: <%= buildpack %>
+        STACKS: "<%= suse_stacks.join(' ') %>"
         GITHUB_PRIVATE_KEY: |
           {{github-private-key}}
         GIT_MAIL: {{github-username}}
